#!/bin/bash
# Enhanced User-Friendly Changelog Generator for Quorum
# Part of the changelog-generator skill - Generates engaging user-focused changelogs

# Default parameters
DAYS=${1:-14}
BRANCH=${2:-cross-platform}
CLAUDE_ENHANCE=${3:-true}
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${4:-$SKILL_DIR/changelogs}"
OUTPUT="$OUTPUT_DIR/quorum-changelog-user-friendly_$(date +%Y-%m-%d_%H-%M).md"
TEXT_OUTPUT="$OUTPUT_DIR/quorum-changelog-user-friendly_$(date +%Y-%m-%d_%H-%M).txt"
COMMITS_FILE="$OUTPUT_DIR/commits-analysis_$(date +%Y-%m-%d_%H-%M).txt"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo "🔍 Analyzing commits for user-friendly changelog from last $DAYS days on $BRANCH branch..."

# Step 1: Collect and filter commits
echo "📝 Step 1: Collecting user-facing commits..."
git log --since="$DAYS days ago" --no-merges --pretty=format:"%H|%s|%b" $BRANCH > temp_all_commits.txt

# Enhanced filtering using skill configuration
USER_FACING_FILTER="$SKILL_DIR/filters/user-facing-commits.txt"
EXCLUDE_FILTER="$SKILL_DIR/filters/exclude-patterns.txt"

# Create filters if they don't exist (will be created by filter generation task)
if [ ! -f "$USER_FACING_FILTER" ]; then
    cat > "$USER_FACING_FILTER" << 'EOF'
✨ feat:
feat:
🐛 fix:
fix:
🎨 style:
style:
🚀 perf:
perf:
Add
Implement
Fix
Improve
Enhance
Update
EOF
fi

if [ ! -f "$EXCLUDE_FILTER" ]; then
    cat > "$EXCLUDE_FILTER" << 'EOF'
playground
audit
component complexity
primitive
typescript
build
lint
✅ task:
task:
📝 doc:
doc:
🧹 chore:
chore:
⚙️ refactor:
refactor:
🧪 test:
test:
📦 build:
build:
EOF
fi

# Build patterns for filtering
include_pattern=""
while IFS= read -r pattern; do
    [ -n "$pattern" ] && [ "${pattern:0:1}" != "#" ] && {
        [ -n "$include_pattern" ] && include_pattern="${include_pattern}|"
        include_pattern="${include_pattern}${pattern}"
    }
done < "$USER_FACING_FILTER"

exclude_pattern=""
while IFS= read -r pattern; do
    [ -n "$pattern" ] && [ "${pattern:0:1}" != "#" ] && {
        [ -n "$exclude_pattern" ] && exclude_pattern="${exclude_pattern}|"
        exclude_pattern="${exclude_pattern}${pattern}"
    }
done < "$EXCLUDE_FILTER"

echo "🔍 Step 2: Filtering important commits..."
grep -iE "\|(${include_pattern})" temp_all_commits.txt | \
grep -viE "(${exclude_pattern})" > important_commits.txt

# Step 2: Create analysis file for Claude
echo "🤖 Step 3: Preparing enhanced analysis for changelog generation..."
cat > "$COMMITS_FILE" << EOF
ENHANCED COMMIT ANALYSIS FOR USER-FRIENDLY CHANGELOG
===================================================

Time Period: Last $DAYS days from $BRANCH branch
Total Commits: $(wc -l < temp_all_commits.txt)
User-Facing Commits: $(wc -l < important_commits.txt)
Generated by: changelog-generator skill

COMMIT CATEGORIZATION:
=====================

EOF

# Function to clean commit messages
clean_commit_message() {
    local message="$1"
    # Strip emoji prefix and type tag (handles both emoji and non-emoji formats)
    echo "$message" | sed -E 's/^[[:space:]]*(✨|🐛|🎨|🚀|🧹|⚙️|🧪|📦|📝|✅|🈶|🌐|⚡|🩹|♿|📱)?[[:space:]]*(feat|fix|style|perf|chore|refactor|test|build|doc|task|i18n):[[:space:]]*//'
}

# Enhanced categorization with better grouping
declare -A categories
declare -A category_descriptions

# Define categories with descriptions (industry-standard)
category_descriptions["features"]="🎉 New Features"
category_descriptions["enhancements"]="✨ Enhancements"
category_descriptions["bugs"]="🐛 Bug Fixes"
category_descriptions["localization"]="🌐 Localization"
category_descriptions["compatibility"]="📱 Compatibility"
category_descriptions["maintenance"]="🔧 Maintenance"

# Categorize commits using conventional commit prefixes
while IFS='|' read -r hash message body; do
    category="enhancements"  # default

    # Precise categorization based on commit type prefixes
    case "$message" in
        *"✨ feat:"*|*"🚀 feat:"*|*"feat:"*) category="features" ;;
        *"🐛 fix:"*|*"🩹 fix:"*|*"fix:"*) category="bugs" ;;
        *"🎨 style:"*|*"style:"*|*"🚀 perf:"*|*"⚡ perf:"*|*"perf:"*) category="enhancements" ;;
        *"🌐 i18n:"*|*"i18n:"*) category="localization" ;;
        *"🧹 chore:"*|*"chore:"*|*"⚙️ refactor:"*|*"refactor:"*) category="maintenance" ;;
        *responsive*|*mobile*|*Mobile*|*touch*|*Touch*|*platform*|*Platform*|*cross-platform*) category="compatibility" ;;
    esac

    clean_message=$(clean_commit_message "$message")
    categories["$category"]+="Commit: ${hash:0:7}|Message: $clean_message"
    if [ -n "$body" ]; then
        categories["$category"]+="|Details: $body"
    fi
    categories["$category"]+="|---"
done < important_commits.txt

# Add categorized commits to analysis file
for category in features enhancements bugs localization compatibility maintenance; do
    if [ -n "${categories[$category]}" ]; then
        echo "${category_descriptions[$category]}" >> "$COMMITS_FILE"
        echo "$(echo "${categories[$category]}" | tr '|' '\n')" >> "$COMMITS_FILE"
        echo "" >> "$COMMITS_FILE"
    fi
done

# Add enhanced Claude instructions
cat >> "$COMMITS_FILE" << 'EOF'

ENHANCED CLAUDE INSTRUCTIONS FOR USER-FRIENDLY CHANGELOG:
=========================================================

You are generating a changelog for Quorum, a decentralized messaging application. Your goal is to create content that excites users about new capabilities while being concise and scannable.

## Target Audience
- End users and beta testers
- Focus on capabilities they can actually use
- Avoid all technical jargon and implementation details

## Required Format

Create both markdown (.md) and text (.txt) versions with this structure:

```markdown
# Updates for Quorum Development

This list is for the web app, these changes are not yet live but you can test them on https://test.quorummessenger.com/

[Only include categories that have relevant commits - skip empty sections]

🎉 **New Features**
- [Major new functionality users can immediately use]

✨ **Enhancements**
- [Improvements to existing features, UI polish, performance]

🐛 **Bug Fixes**
- [Issues resolved that were affecting user experience]

🌐 **Localization**
- [Language and translation updates]

📱 **Compatibility**
- [Mobile, browser, and cross-platform improvements]

🔧 **Maintenance**
- [Behind-the-scenes improvements and optimizations]

---
*Based on X key improvements from Y commits*
```

## Writing Guidelines

### DO:
✅ **Keep it SHORT**: Maximum 1-2 bullet points per category
✅ **Focus on user benefits**: "What can I do now that I couldn't before?"
✅ **Use active language**: "Search member lists instantly" not "Member lists can now be searched"
✅ **Group related commits**: Multiple small improvements → one concise description
✅ **Write for excitement**: Make users want to try the new features

### DON'T:
❌ **Use technical terms**: No "refactor", "implement", "optimize", "component", etc.
❌ **Mention file names**: No src/components/whatever.tsx references
❌ **Write long descriptions**: Keep bullet points under 15 words when possible
❌ **Include obvious things**: Don't state "works better now" without specifics

### Subcategory Emojis (REQUIRED for grouped features):
When grouping multiple related changes under a subcategory heading, ALWAYS prefix with a relevant emoji:

**Common subcategory emoji mappings:**
- 📬 Unread/Notifications    - 💬 Messages/Chat/DMs
- 🧭 Navigation              - 🏷️ Mentions/Tags
- 🛡️ Safety/Security         - ✏️ Composer/Input
- 📱 Mobile                  - 🎨 Visual/UI/Styling
- 🔍 Search                  - ⚙️ Settings
- 👥 Users/Members           - 📁 Channels/Spaces
- 🔔 Alerts                  - 📌 Pinning
- 🔗 Links/Sharing           - ⌨️ Keyboard/Shortcuts

### Example Transformations:

**Multiple commits about pinning:**
- "Add pin message functionality"
- "Implement pin UI component"
- "Add unpin capability"

**Becomes:**
🎉 **New Features**

📌 Message Pinning
- Pin important messages for easy access

**Multiple enhancement commits:**
- "🎨 style: improve button styling"
- "🎨 style: enhanced modal animations"
- "🎨 style: update color scheme"

**Becomes:**
✨ **Enhancements**

🎨 Visual Polish
- Smoother animations and updated visual design

## Output Requirements

1. **Save markdown version** to the path specified in the script parameters
2. **Save text version** (remove markdown formatting, keep emojis)
3. **Include footer** with commit statistics
4. **Only include categories** that have actual commits (skip empty sections)
5. **Maximum 2 bullet points per category** - be selective and impactful
6. **Always include Quorum links footer** at the very end:
   ```
   ---
   Quorum links: https://iri.quest/quorum
   ```

## Quality Check
Before finalizing, ask yourself:
- Would a non-technical user understand and get excited about this?
- Is each bullet point under 15 words?
- Does it focus on user capabilities, not technical achievements?
- Would users want to test these features?

Generate the changelog now, focusing on making users excited about what they can do with these improvements!
EOF

echo "✅ Enhanced commit analysis saved: $COMMITS_FILE"
echo "📊 Found $(wc -l < important_commits.txt) user-facing commits out of $(wc -l < temp_all_commits.txt) total"

# Cleanup temp files
rm temp_all_commits.txt important_commits.txt

# Claude enhancement instructions
if [ "$CLAUDE_ENHANCE" = "true" ]; then
    echo ""
    echo "🤖 READY FOR CLAUDE ENHANCEMENT:"
    echo "================================"
    echo ""
    echo "The commit analysis is ready. To generate the user-friendly changelog:"
    echo ""
    echo "1. Use this command with Claude Code:"
    echo "   \"Generate a user-friendly changelog using the analysis in $COMMITS_FILE\""
    echo ""
    echo "2. Or manually review the analysis file and ask Claude:"
    echo "   \"Create a user-friendly changelog based on the commit analysis\""
    echo ""
    echo "3. Claude will automatically save the results to:"
    echo "   - Markdown: $OUTPUT"
    echo "   - Text: $TEXT_OUTPUT"
    echo ""
    echo "💡 The skill outputs are now contained within the skill directory!"
else
    echo ""
    echo "📋 Basic analysis complete. For enhanced changelog generation:"
    echo "   Run with --claude-enhance flag or use the changelog-generator skill"
fi

# Show preview if requested
if [[ "$1" == "--show" ]] || [[ "$2" == "--show" ]] || [[ "$3" == "--show" ]] || [[ "$5" == "--show" ]]; then
    echo ""
    echo "📋 Commit Analysis Preview:"
    echo "=========================="
    head -50 "$COMMITS_FILE"
    echo "..."
    echo ""
    echo "Full analysis available in: $COMMITS_FILE"
fi