import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Flex, Text, Icon } from '../../components/primitives';
import { DevNavMenu } from '../DevNavMenu';
import { MarkdownViewer } from './MarkdownViewer';
import { FilterableList } from './components/FilterableList';
import { useMarkdownFiles, type MarkdownFile } from './hooks/useMarkdownFiles';

/**
 * Browser for `.agents/issues/` — bugs and tasks together.
 *
 * Replaces the old separate Tasks and Bugs pages. The two used to be different
 * folders; they are now one folder plus a `type:` field, so splitting them into
 * two pages would mean reading the same tree twice and hiding half the backlog
 * behind a tab. They are one list with a type filter instead.
 */
export const Issues: React.FC = () => {
  const { issueId } = useParams<{ issueId?: string }>();
  const navigate = useNavigate();
  const [selectedFile, setSelectedFile] = useState<MarkdownFile | null>(null);

  const { files: issueFiles, loading, error, findBySlug } =
    useMarkdownFiles('issues');

  // Handle URL-based navigation
  useEffect(() => {
    if (issueId && !loading) {
      const file = findBySlug(issueId);
      if (file) {
        setSelectedFile(file);
      } else {
        // Invalid issue ID, redirect to list
        navigate('/dev/issues', { replace: true });
      }
    } else {
      setSelectedFile(null);
    }
  }, [issueId, loading, findBySlug, navigate]);

  const handleBackToList = () => {
    navigate('/dev/issues');
  };

  if (selectedFile) {
    return (
      <MarkdownViewer
        filePath={selectedFile.path}
        onBack={handleBackToList}
        title={selectedFile.title}
        file={selectedFile}
      />
    );
  }

  return (
    <div className="min-h-screen bg-app">
      <DevNavMenu currentPath={window.location.pathname} />
      <div className="p-6 mx-auto max-w-6xl">
        <div className="text-center mb-8">
          <Flex justify="center" gap="sm" className="mb-4">
            <Icon name="clipboard-list" size="2xl" className="text-strong" />
            <Text as="h1" variant="strong" size="3xl" weight="bold">
              Issues
            </Text>
          </Flex>
          <Text as="p" variant="main" size="lg" className="mb-2" align="center">
            Bugs and Tasks
          </Text>
          <Text as="p" variant="subtle" align="center">
            Browse all issues from .agents/issues/
          </Text>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="text-center py-12">
            <Icon
              name="spinner"
              size="2xl"
              className="text-accent mx-auto mb-4"
            />
            <Text variant="main" size="lg">
              Loading issues...
            </Text>
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="bg-danger/10 border border-danger/30 rounded-lg p-6 mb-8">
            <Flex gap="sm" align="center" className="mb-2">
              <Icon name="warning" size="md" className="text-danger" />
              <Text variant="strong" size="lg" className="text-danger">
                Error Loading Issues
              </Text>
            </Flex>
            <Text variant="main" size="sm" className="mb-4">
              {error}
            </Text>
            <Text variant="subtle" size="sm">
              The manifest is generated by <code>yarn scan-docs</code>. Re-run it
              if the tree has changed.
            </Text>
          </div>
        )}

        {/* Filterable Issue List */}
        {!loading && (
          <FilterableList
            files={issueFiles}
            section="issues"
            basePath="/dev/issues"
          />
        )}
      </div>
    </div>
  );
};
