/**
 * Action Queue Types
 *
 * Types for the persistent background action queue system.
 * See: .agents/tasks/background-action-queue.md
 */

export type ActionType =
  // Core actions - sending messages
  | 'send-channel-message' // Receives signed message, Triple Ratchet encrypt
  | 'send-dm' // Receives signed message, Double Ratchet encrypt
  | 'save-user-config' // UserConfig: folders, sidebar order, user preferences (UserSettingsModal)
  | 'update-space' // Space settings: name, description, roles, emojis, stickers (SpaceSettingsModal)

  // Moderation
  | 'kick-user'
  | 'mute-user'
  | 'unmute-user'

  // Message actions
  | 'reaction'
  | 'pin-message'
  | 'unpin-message'
  | 'edit-message'
  | 'delete-message';

export type TaskStatus = 'pending' | 'processing' | 'completed' | 'failed';

export interface QueueTask {
  id?: number; // Auto-generated by IndexedDB
  taskType: ActionType;

  // Plaintext context - browser sandbox provides sufficient isolation
  // See "Why No Encryption-at-Rest?" in task doc
  context: Record<string, unknown>;

  // Grouping key for serial processing within group
  key: string; // e.g., "spaceId/channelId" for messages

  // Status tracking
  status: TaskStatus;
  retryCount: number;
  maxRetries: number;
  nextRetryAt: number;

  // Timestamps
  createdAt: number;
  processedAt?: number;
  processingStartedAt?: number; // For crash recovery & multi-tab gating

  // Error info
  error?: string;
}

export interface QueueStats {
  pending: number;
  processing: number;
  failed: number;
  completed: number;
  total: number;
}
